# Generated by Django 5.0.3 on 2024-03-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
